# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='sreet_address',
            new_name='street_address',
        ),
    ]
